### ISSUE TITLE
Add humans.txt to the page

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [NetDevelopersPoland/NetDevPLWebsite#27]
http://humanstxt.org/

**Comment by tkestowicz** [comment]
Do we really need this?

**Comment by pawlos** [comment]
@tkestowicz probably not, but didn't hurt having it too..

**Comment by jedmac** [comment]
In my opinion it is completely unuseful and I would remove it as we have our contributors list directly on a website. Furthermore, we also have a link to a github repository where we can point to it.
