### ISSUE TITLE
Integrate with codecov

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [NetDevelopersPoland/NetDevPLWebsite#40]
@pawelklimczyk Could you please visit https://codecov.io/, log in via github and integrate repo with codecov?

**Comment by pawlos** [comment]
@lukasz-pyrzyk I think I can do it too, but what we will gain with this integration?

**Comment by lukasz-pyrzyk** [comment]
I wanted to add OpenCover to generate reports about code coverage and send it to codecov, but @pawelklimczyk is working on it right now. 

Except classic code coverage result and badge for github, we will see code coverage of incoming PR

**Comment by pawlos** [comment]
@lukasz-pyrzyk ok, sounds nice

**Comment by pawelklimczyk** [comment]
still stuff to do. 🎱

**Comment by pawlos** [comment]
@pawelklimczyk if you're busy I can do this (I think :])

**Comment by lukasz-pyrzyk** [comment]
@pawelklimczyk i can help you if you have any problems

**Comment by pawelklimczyk** [comment]
done.
