### ISSUE TITLE
Rename 'Wydarzenia lokalne'

### ISSUE THREAD

**Issue by pawlos** [NetDevelopersPoland/NetDevPLWebsite#41]
I believe that we should rename this page to just 'Wydarzenia' as there are currently events like Build Stuff, which is not local in my sense of closeness. Or we are talking about our [local group](https://en.wikipedia.org/wiki/Local_Group) distances :)

If we're fine with the change that I can create a PR or we should only stick to really local events (+ Internet?)

**Comment by pawelklimczyk** [comment]
Done
