### ISSUE TITLE
NLog does not work on Linux

### ISSUE THREAD

**Issue by pawelklimczyk** [NetDevelopersPoland/NetDevPLWebsite#50]
Same configuration for Windows and Linux. Does not work on linux. Output is empty.

**Mono version**
> Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue Mar 15 11:39:54 EDT 2016)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
>         TLS:           __thread
>         SIGSEGV:       altstack
>         Notifications: epoll
>         Architecture:  amd64
>         Disabled:      none
>         Misc:          softdebug
>         LLVM:          supported, not enabled.
>         GC:            sgen

**Comment by lukasz-pyrzyk** [comment]
NLog had a problem with working on Mono. I see that we are using two versions:

<Reference Include="NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c, processorArchitecture=MSIL">
<package id="NLog" version="4.3.10" targetFramework="net452" />

Please update to the newest pre version - NLog 4.4.0-betaV15.

**Comment by pawelklimczyk** [comment]
NLog 4.4.0-betaV15 - works fine ?

**Comment by lukasz-pyrzyk** [comment]
I had similar problem with .NET Core on Mono. After upgrade it  works fine

**Comment by pawelklimczyk** [comment]
Done
