### ISSUE TITLE
HTTP address parsing issues

### ISSUE THREAD

**Issue by pawelklimczyk** [NetDevelopersPoland/NetDevPLWebsite#58]
![image](https://cloud.githubusercontent.com/assets/1084668/21144458/fe857a6c-c14a-11e6-8c6a-e89cc8ee1352.png)

Address with @ should be correctly parsed as http address.

**Comment by pawlos** [comment]
also there's an issue with ,(comma)

![image](https://user-images.githubusercontent.com/1296768/29966453-3f5897b4-8f12-11e7-9c13-56f3448b27f4.png)

**Comment by pawlos** [comment]
Now it takes too much producing the link like http://www.empik.com/praca-z-zastanym-kodem-najlepsze-techniki-michael-feathers,p1143740022,ksiazka-p%20. I'll investigate if more can be done here.
