### ISSUE TITLE
Last update timestamp for page

### ISSUE THREAD

**Issue by pawelklimczyk** [NetDevelopersPoland/NetDevPLWebsite#79]
Following pages should have information when they were last updated:

- http://netdevelopers.pl/groups
- http://netdevelopers.pl/blogs
- http://netdevelopers.pl/facebook

Background jobs should update that field.

Possible solution: After job is executed a entry for key-value in mongodb table is updated. This entry is read  by nancyfx when page is requested.

**Comment by PawelHaracz** [comment]
I can do it

**Comment by pawelklimczyk** [comment]
Great, go for it!

**Comment by pawlos** [comment]
@pawelklimczyk is this issue resolved after the merge? or still some work needs to be done?

**Comment by pawelklimczyk** [comment]
i think it can be resolved
