### ISSUE TITLE
Create new section 'Youtube channels'

### ISSUE THREAD

**Issue by GKotfis** [NetDevelopersPoland/NetDevPLWebsite#90]
Maybe it's a good idea to add new section with youtube channels related to .net? I wanted to add my new channel but I don't know if "Media -> Webcasts" is good place for that ...

**Comment by pawlos** [comment]
I think channels might be too broad as not always the whole channel is about .net, but if you have a playlist on you channel that covers a specific topic then I think it's more than ok to add it there.

**Comment by pawelklimczyk** [comment]
@GKotfis **webcasts** is the dedicated place for those. 

We could redesign **webcasts** page so it is a table with YT channel on left and description on right. Sorted by newest videos (newest videos on top).

Ofc you can add a channel as next to the list now as well.

**Comment by GKotfis** [comment]
Thanks for the answers.
